// Generated by Wrangler on Fri Dec 20 2024 18:31:45 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface Env {
	PROJECT_URL: "https://wbhccwyuwdverkpmsuvt.supabase.co";
	SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiaGNjd3l1d2R2ZXJrcG1zdXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2OTM4MjEsImV4cCI6MjA1MDI2OTgyMX0.Iz4N4a9HSu_O6nhchBg5DmDH8bO6Ehvz2Wb-y-qF1J4";
}
